In [1]:
import pandas as pd

In [18]:
# import csv, first column as datetime, second as float
df = pd.read_csv("balance.csv", sep=",", parse_dates=[0], decimal=",", thousands=" ")

In [22]:
df

        dateOp  amount
0   2025-02-24    0.30
1   2025-02-24   55.86
2   2025-02-21   -8.00
3   2025-02-21  -59.04
4   2025-02-20  -25.95
..         ...     ...
198 2024-01-22   -1.50
199 2024-01-15  -34.30
200 2024-01-15  -20.00
201 2024-01-02   40.00
202 2024-01-02   50.00

[203 rows x 2 columns]

In [ ]:
df["year_month"] = df["dateOp"].dt.to_period("M")

In [ ]:
expenses_df = df[df["amount"] < 0]

In [ ]:
monthly_expenses = expenses_df.groupby("year_month")["amount"].sum().reset_index()

In [28]:
monthly_expenses

   year_month   amount
0     2024-01   -55.80
1     2024-02   -15.58
2     2024-03    -6.52
3     2024-04   -78.79
4     2024-05  -311.71
5     2024-06  -332.12
6     2024-08 -1179.00
7     2024-09  -496.40
8     2024-10  -799.09
9     2024-11  -273.01
10    2024-12  -489.03
11    2025-01  -662.64
12    2025-02  -330.32

In [5]:
import datetime


df.dateOp.astype(datetime.datetime)

TypeError: dtype '<class 'datetime.datetime'>' not understood